openapi: 3.0.3
info:
  title: demo-clean-architecture-api
  version: '1.0'
  description: 認証認可機能を持つ基本的なデモAPI
  contact:
    name: Yui
    email: 65758369+semba-yui@users.noreply.github.com
    url: 'https://github.com/semba-yui/demo-clean-architecture-dotnet'
servers:
  - url: 'http://localhost:8080'
    description: Local
paths:
  /api/demo-clean-architecture/v1.0/auth/user/register:
    post:
      summary: ユーザー登録
      operationId: post-api-demo-clean-architecture-v1.0-user-register
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    user_id: 1
                properties:
                  user_id:
                    type: integer
                    minimum: 1
                    example: 1
                    format: int32
                required:
                  - user_id
              examples:
                Example 1:
                  value:
                    user_id: 1
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    code: REGISTRATION_FAILED
                    message: アカウント登録に失敗しました
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                REGISTRATION_FAILED:
                  value:
                    code: REGISTRATION_FAILED
                    message: アカウント登録に失敗しました
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  user_name: test-user
                  email: aaa1@example.co.jp
                  password: p@ssWord
              properties:
                user_name:
                  type: string
                  maxLength: 20
                email:
                  type: string
                  example: user@example.co.jp
                  format: email
                  maxLength: 50
                password:
                  type: string
                  format: password
                  maxLength: 30
                  minLength: 8
                  example: P@ssW0rd
              required:
                - user_name
                - email
                - password
            examples:
              Example 1:
                value:
                  user_name: ユーザー名
                  email: user@example.co.jp
                  password: P@ssW0rd
        description: ''
      parameters: []
      description: ユーザー登録を行う。
      tags:
        - user
    parameters: []
  /api/demo-clean-architecture/v1.0/auth/login:
    post:
      summary: ログイン
      operationId: post-api-demo-clean-architecture-v1.0-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                    refresh_token: dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4uLi4=
                    is_two_factor_enabled: true
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  is_two_factor_enabled:
                    type: boolean
                required:
                  - access_token
                  - refresh_token
                  - is_two_factor_enabled
              examples:
                Example 1:
                  value:
                    access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                    refresh_token: dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4uLi4=
                    is_two_factor_enabled: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    code: INVALID_PARAMETER
                    message: Invalid parameter
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                INVALID_PARAMETER:
                  value:
                    code: INVALID_PARAMETER
                    message: Invalid parameter
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    code: UNAUTHORIZED
                    message: Unauthorized Error
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                UNAUTHORIZED:
                  value:
                    code: UNAUTHORIZED
                    message: Unauthorized Error
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    code: INTERNAL_ERROR
                    message: Internal Server Error
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                INTERNAL_ERROR:
                  value:
                    code: INTERNAL_ERROR
                    message: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  email: user@example.com
                  password: P@ssW0rd
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 50
                  example: user@example.com
                password:
                  type: string
                  format: password
                  maxLength: 30
                  minLength: 8
                  example: P@ssW0rd
              required:
                - email
                - password
            examples:
              Example 1:
                value:
                  email: user@example.com
                  password: P@ssW0rd
        description: ''
      parameters: []
      description: ログインを行う。
      tags:
        - auth
    parameters: []
components:
  schemas: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: user
  - name: auth
